name: Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: ./yarn.lock
          cache: 'yarn'

      - name: Install
        shell: 'bash'
        working-directory: ./
        run: yarn install --immutable

      - name: Build
        shell: 'bash'
        working-directory: ./
        run: yarn run build

      - name: Lint:js
        shell: 'bash'
        working-directory: ./
        run: yarn run lint

      - name: Lint:style
        shell: 'bash'
        working-directory: ./
        run: yarn run lint:style

      - name: Test
        shell: 'bash'
        working-directory: ./
        run: yarn run test
