name: Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        shell: "bash"
        working-directory: ./
        run: bun install --frozen-lockfile

      - name: Build
        shell: "bash"
        working-directory: ./
        run: bun run build

      - name: Lint
        shell: "bash"
        working-directory: ./
        run: bun run lint

      - name: Test
        shell: "bash"
        working-directory: ./
        run: bun run test